# Generated by Django 4.1.1 on 2022-10-03 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 10, 30, 51, 514050, tzinfo=datetime.timezone.utc)),
        ),
    ]
