# Generated by Django 4.1.1 on 2022-10-04 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 10, 44, 54, 993748, tzinfo=datetime.timezone.utc)),
        ),
    ]
